### ISSUE TITLE
Implement Thermostat functionality

### ISSUE THREAD

**Issue by cooperbell** [JIongbaiLiu/Senior_Design#19]
In the beginning of the main `loop()` method, use `analogRead()` from one of the analog pins on the Arduino
 - Ex. code for getting the temp into Fahrenheit format (make sure tempF is an int)
 ```
  reading = analogRead(tempPin);
  tempF = (reading / 9.31 * 1.8 + 32);
```

If the temp changes, then calling [`printCurrentTemp()`](https://github.com/JIongbaiLiu/Senior_Design/blob/58476040bef37dc57815bb635811c296fd2c0023/Lab3/Thermostat/Thermostat.ino#L641) should do the trick

**Comment by lukehermann** [comment]
Temp sensor reads temp correctly and converts it to the nearest whole number.
